tango_with_django_project/rango/urls.py
from django.urls import path 
from rango import views 

app_name = 'rango'

urlpatterns = [
	path('', views.index,name='index' ),
	path('about/', views.about, name='about'),
	path('category/<slug:category_name_slug>/',
			views.show_category, name='show_category'),
	path('add_category/', views.add_category, name='add_category'),
	path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
	# path('register/', views.register, name='register'),
	# path('login/', views.user_login , name='login'),
	path('restricted/', views.restricted , name='restricted'),
	# path('logout/', views.user_logout , name='logout'),


]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', views.index ,name='index'),
	path('rango/',include('rango.urls')),
	path('accounts/', include('registration.backends.simple.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class Category (models.Model):
	Name_Max_Length = 128
	name = models.CharField(max_length=Name_Max_Length, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)
	
	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'categories'
	
	def __str__(self):
		return self.name


class Page(models.Model):
	Title_Max_Length = 128
	URL_Max_Length = 200
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=Title_Max_Length)
	url = models.URLField()
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.title

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	def __str__(self):
		return self.user.username

		

tango_with_django_project/rango/forms.py
from django import forms 
from rango.models import Page, Category , UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.Name_Max_Length,
    						help_text='Please enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=Page.Title_Max_Length,
							help_text='Please enter the title of the page.')
	url = forms.URLField(max_length=Page.URL_Max_Length,
	   						help_text='Please enter the url for the page.')
	views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
	
	def clean(self):
		cleaned_data = self.cleaned_data
		url = cleaned_data.get('url')

		if url and not url.startswith('https://'):
			url = f'https://{url}'
			cleaned_data['url'] = url 
		return cleaned_data	
	
	class Meta:
		model = Page
		exclude = ('category',)


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website','picture',)

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from rango.models import Category ,Page
from rango.forms import CategoryForm ,PageForm
# from django.contrib.auth import authenticate , login  , logout
from django.contrib.auth.decorators import login_required
from datetime import datetime 

def get_server_side_cookie(request, cookie, default_val=None):
	val = request.session.get(cookie)
	if not val:
		val = default_val 
	return val 

def visitor_cookie_handler(request):
	visits =  int(get_server_side_cookie(request, 'visits' , '1'))

	last_visit_cookie = get_server_side_cookie(request ,
											 'last_visit', 
											 str(datetime.now()))
	last_visit_time = datetime.strptime(last_visit_cookie[:-7],
										'%Y-%m-%d %H:%M:%S')
	if (datetime.now() - last_visit_time).days >0:
		visits = visits + 1
		request.session['last_visit'] = str(datetime.now())
	else:
		request.session['last_visit'] = last_visit_cookie

	request.session['visits'] = visits 

	

def index(request):
	category_list = Category.objects.order_by('-likes')[:5]
	page_list = Page.objects.order_by('-views')[:5]
	most_liked_category = Category.objects.order_by('-likes')[0]
	most_viewed_page = Page.objects.order_by('-views')[0]

	context_dict= {}
	context_dict ['boldmessage'] = 'crunchy , creamy , cookie , candy , cupcake'
	context_dict['categories'] = category_list
	context_dict['pages'] = page_list
	context_dict['most_liked_category'] = most_liked_category
	context_dict['most_viewed_page'] = most_viewed_page
	
	
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	response = render(request, 'rango/index.html' , context=context_dict)
	return response

def about(request):
	context_dict = {'myname':'ahmad ali'}
	return render(request,'rango/about.html',context=context_dict)

def show_category(request, category_name_slug):
	context_dict = {}

	try:
		category = Category.objects.get(slug=category_name_slug)

		pages = Page.objects.filter(category=category)

		context_dict['pages'] = pages
		context_dict['category'] = category

	except Category.DoesNotExist:
		context_dict['category'] = None
		context_dict['pages'] = None

	return render(request,'rango/category.html', context=context_dict)

@login_required
def add_category(request):
	form = CategoryForm()

	if request.method == 'POST':
		form = CategoryForm(request.POST)
		if form.is_valid():
			form.save(commit=True)
			return redirect('/rango/')
		else:
			print(form.errors)
	return render(request, 'rango/add_category.html',{'form':form})

@login_required
def add_page(request , category_name_slug):
	try:
		category = Category.objects.get(slug=category_name_slug)
	except Category.DoesNotExist:
		category= None
	if category is None:
		return redirect('/rango/')
	form = PageForm()

	if request.method =='POST':
		try:
			post_exist = Page.objects.get(title=request.POST['title'])
			return HttpResponse("Page already exist")
		except Page.DoesNotExist:
			form = PageForm(request.POST)
			if form.is_valid():
				if category:
					page = form.save(commit=False)
					page.category = category
					page.views = 0
					page.save()
					return redirect(reverse('rango:show_category',
											kwargs={'category_name_slug':
													category_name_slug}))
			else:
				print(form.errors)

	context_dict = {'form':form, 'category':category}
	return render(request, 'rango/add_page.html', context=context_dict)
@login_required
def restricted(request):
	return render(request, 'rango/restricted.html')


# def register(request):
# 	# A boolean value for telling the template
# 	# whether the registration was successful.
# 	# Set to False initially. Code changes value to
# 	# True when registration succeeds.
# 	registered = False

# 	if request.method == 'POST':
# 		user_form = UserForm(request.POST)
# 		profile_form = UserProfileForm(request.POST)

# 		if user_form.is_valid() and profile_form.is_valid():
# 			user = user_form.save()
# 			user.set_password(user.password)
# 			user.save()
# 			profile = profile_form.save(commit=False)
# 			profile.user = user 
# 			if 'picture' in request.FILES:
# 				profile.picture = request.FILES['picture']

# 			profile.save()
# 			registered = True 
# 		else:
# 			print(user_form.errors, profile_form.errors)
# 	else:
# 		user_form = UserForm()
# 		profile_form = UserProfileForm()
# 	return render(request,
# 				'rango/register.html',
# 				context = {'user_form':user_form,
# 							'profile_form':profile_form,
# 							'registered':registered})


# def user_login(request):
# 	if request.method == 'POST':
# 		username = request.POST.get('username')
# 		password = request.POST.get('password')
# 		user = authenticate(username=username , password=password)

# 		if user:
# 			if user.is_active:
# 				login(request, user)
# 				return redirect(reverse('rango:index'))
# 			else:
# 				return HttpResponse("your rango account is disabled.")
# 		else:
# 			print(f"invalid login details : {username}, {password}")
# 			return HttpResponse("invalid login details supplied")
# 	else:
# 		return render(request,'rango/login.html')



# @login_required
# def user_logout(request):
# 	logout(request)
# 	return redirect(reverse('rango:index'))

tango_with_django_project/templates/rango/about.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title_block %}
	About Page
{% endblock title_block %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Rango says...</h1>
			<div>
				<h2 class="h2">
					{% if user.is_authenticated %}
						howdy {{ user.username }}!
					{% else %}
						hey there partner!
					{% endif %}
				</h2>
				<strong>This is rango about page</strong>
			</div>
		</div>
	</div>
	<div>
		<a href="{% url 'rango:index' %}">Main rango</a><br/>
		<img src="{% static 'images/rango_camlion_image.jpg' %}"
					 alt="Picture of rango"/>
				<img src="/media/images/cat.jpg"
					alt="Picture of a cat" />
	</div>
{% endblock body_block %}

tango_with_django_project/templates/rango/add_category.html
{% extends "rango/base.html" %}
{% block title_block %}
	Adding a Category
{% endblock title_block %}
{% block body_block %}
	<h1>Add a Category</h1>
	<div>
		<form id="category_form" method="POST" action="/rango/add_category/">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}
				{{ field }}
			{% endfor %}
			<input type="submit" name="submit" value="Create Category" />
		</form>
	</div>
{% endblock body_block %}

tango_with_django_project/templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title_block %}
	Adding a Page to {{category.name}}
{% endblock title_block %}
{% block body_block %}
	<h1>Add Page to {{ category.name }} Category</h1>
	<div>
		<form id="page_form" method="POST" action="/rango/category/{{category.slug}}/add_page/">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden}}
			{% endfor %}
			{% for field in form.visible_fields %}
			{{ field.errors }}
			{{ field.help_text }}
			{{ field }}	
			{% endfor %}
			<input type="submit" name="submit" value="Create Page" />
		</form>
	</div>
{% endblock body_block %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul class="nav flex-column">
	{% if categories %}
		{% for c in categories %}
			{% if c == current_category %}
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>{{ c.name }}
					</a>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>{{ c.name }}
					</a>
				</li>
			{% endif %}
		{% endfor %}
	{% else %}
		<li class="nav-item">There are no categories present.</li>
	{% endif %}
</ul>

tango_with_django_project/templates/rango/category.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title_block %}
	{% if category %}
		{{category.name}}
	{% else %}
		Unown Category
	{% endif %}
{% endblock title_block %}

{% block body_block %}
	{% if category %}
		<h1>{{category.name}}</h1>
		{% if pages %}
		<ul>
			{% for page in pages %}
				<li><a href="{{page.url}}">{{page.title}}</a></li>
			{% endfor %}
		</ul>
		{% else %}
			<strong>No pages currently in category.</strong>
		{% endif %}
			{% if user.is_authenticated %}
				<a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br/>
			{% endif %}
		
		{% else %}
			the specifed category does not exist 
	{% endif %}
{% endblock body_block %}

tango_with_django_project/templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title_block %}
	Home Page
{% endblock title_block %}
{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Rango says...</h1>
			<div>
				<h2 class="h2">
					{% if user.is_authenticated %}
						howdy {{ user.username }}!
					{% else %}
						hey there partner!
					{% endif %}
				</h2>
				<strong>{{ boldmessage }}</strong>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="card mb-6">
					<div class="card-body">
						<h2>Most Liked Categories</h2>
						<p class="card-text">
							{% if categories %}
								<ul class="list-group">
								{% for category in categories %}
									<li>
										<a href="{% url 'rango:show_category' category.slug %}">
										{{ category.name }}</a>
									</li>
								{% endfor %}
								</ul>
							{% else %}
								<strong>There are no categories present.</strong>
							{% endif %}
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card mb-6">
					<div class="card-body">
						<h2>Most Viewed Pages</h2>
						<p class="card-text">
							{% if pages %}
								<ul class="list-group">
								{% for page in pages %}
									<li class="list-group-item">
										<a href="{{ page.url }}">{{ page.title }}</a>
									</li>
								{% endfor %}
								</ul>
							{% else %}
								<strong>There are no pages present.</strong>
							{% endif %}
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>	
{% endblock body_block %}

tango_with_django_project/templates/rango/login.html
{# {% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
	Login
{% endblock title_block %}

{% block body_block %}
	<h1>Login to Rango</h1>
	<form id="login_form" method="post" action="{% url 'rango:login' %}">
		{% csrf_token %}
		Username : <input type="text" name="username" value="" size="50" />
		<br/>
		Password : <input type="password" name="password" value="" size="50" />
		<br/>
		<input type="submit" name="submit" />

	</form>
{% endblock body_block %} #}

tango_with_django_project/templates/rango/old-base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
	<head lan="eng">
		<meta charset="utf-8"/>
		<title>Rango -
			{% block title_block %}
				how to tango with django 
			{% endblock title_block %}
		</title>
	</head>
	<body>
		<div>
			{% block body_block %}
				
			{% endblock body_block %}
		</div>
		<div>
			{% block sidebar_block %}
				{% get_category_list category %}
			{% endblock sidebar_block %}
		</div>
		<hr/>
		<div>
			<ul>
				{% if user.is_authenticated %}
					<li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
					<li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
					<li><a href="{% url 'rango:add_category' %}">Add a new category</a></li>
					<li><a href="{% url 'auth_password_change' %}">Password Change</a></li>
				{% else %}
					<li><a href="{% url 'registration_register' %}">Sign Up</a></li>
					<li><a href="{% url 'auth_login' %}">Login</a></li>
				{% endif %}
					
					<li><a href="{% url 'rango:about' %}">About Page</a></li>
					<li><a href="{% url 'rango:index' %}">Index</a></li>
			</ul>
		</div>

	</body>
</html>

tango_with_django_project/templates/rango/register.html
{# {% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
	Register
{% endblock title_block %}

{% block body_block %}
	<h1>Register For Rango</h1>
	{% if registered %}
		rango says: <strong>thank for regustering</strong>
		<a href="{% url 'rango:index' %}">return to the home page</a>
	{% else %}
		Rango says : <strong>Register Here</strong><br/>
		<form id='user_form' method="post" action="{% url 'rango:register' %}"
		enctype="multipart/form-data">
			{% csrf_token %}
			{{ user_form.as_p}}
			{{ profile_form.as_p}}
			<input type="submit" name="submit" value="Register"/>
		</form>
		
	{% endif %}
	

{% endblock body_block %} #}

tango_with_django_project/templates/rango/restricted.html
{% extends "rango/base.html" %}	
{% load staticfiles %}

{% block title_block %}
	Restricted page
{% endblock title_block %}

{% block body_block %}
	<h1>if Your loged in you can see this text </h1>
{% endblock body_block %}